language: java

script: ./gradlew build

jdk:
  - oraclejdk8

# Travis uses old JDK which causes a bug. Avoid it by installing newest version
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  slack: reportportal:fl6xWHVQp1jvsMmCJxYW9YKP

after_success:
  - bash <(curl -s https://codecov.io/bash)
